### ISSUE TITLE
Refactoring todo list

### ISSUE THREAD

**Issue by nickhsine** [readr-media/react#34]
### Optimization
1. [ ] reuse common bundles, such as `react`, `react-dom`, `draft-js`, `lodash`, `immutable`, .etc, large bundles.
2. [ ] lazy load optional webpack bundles, such as `draft-js`(more than 150kb)
3. [ ] do not load unnecessary bundles（因為我們目前 bundles 產生是透過 `packages/embed-code-generator`，它的 main bundle 會有 `feeback`, `qa-list` 和 `questionnaire` 的程式碼，但使用者可能只需要 `feedback` 的 embed code ）

### Code Refactoring
- [ ] make all codes pass eslint and prettier
- [ ] add prettier, eslint commit hook
- [ ] extract `packages/questionnaire/src/react-components/draft` to be an pkg under `packages/draft-editor`

### Infrustructure
- [ ] add CI to build sub pkgs, such as `@readr-media/react-feedback` if there are new commits in the repo.
- [ ] automatically update `@readr-media/react-embed-code-generator` pkg if there is any sub pkg (`@readr-media/react-feedback`, `@readr-media/react-qa-list`, `@readr-media/react-questionnaire`) upgraded.
- [ ] - [ ] automatically update `@readr-media/questionnaire` and `@readr-media/react-qa-list` pkg if`@readr-media/draft-editor` is upgraded.

**Comment by nickhsine** [comment]
> - [x] reuse common bundles, such as react, react-dom, draft-js, lodash, immutable, .etc, large bundles.
> - [x] lazy load optional webpack bundles, such as draft-js(more than 150kb)
> - [x] do not load unnecessary bundles（因為我們目前 bundles 產生是透過 packages/embed-code-generator，它的 main bundle 會有 feeback, qa-list 和 questionnaire 的程式碼，但使用者可能只需要 feedback 的 embed code ）

PR https://github.com/readr-media/react/pull/91 completes the above items.
